version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: 1
  parameter-store:
    REGISTRY_URI: "/ecr/registry_uri"
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin $REGISTRY_URI
      - image_tag=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - ${CODEBUILD_SRC_DIR}/scripts/build.sh